### ISSUE TITLE
Container won't start: Sub-message not read correctly

### ISSUE THREAD

**Issue by tmontney** [AddictedCS/soundfingerprinting#129]
I was fingerprinting all my tracks on a network share, and it got stuck at around 1,100. My PC was pretty low on space at that point, perhaps that did it? Either way, the container won't start. I've even tried creating a new one, still doesn't start.
**docker start "ef929a2e-8234-47e7-8973-a86e28512f6a" -ai**
```
2019-11-25 04:16:29.2301 Info Configuring ThreadPool with MinWorkThreads: 50, MinIoThreads: 50
2019-11-25 04:16:29.3969 Info Reading running replication log from ./data/replication/log.log

Unhandled Exception: ProtoBuf.ProtoException: Sub-message not read correctly
   at ProtoBuf.ProtoReader.EndSubItem(SubItemToken token, ProtoReader reader) in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 644
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type) in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 618
   at proto_9(Object , ProtoReader )
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type) in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 607
   at proto_10(Object , ProtoReader )
   at ProtoBuf.Meta.TypeModel.DeserializeWithLengthPrefix(Stream source, Object value, Type type, PrefixStyle style, Int32 expectedField, TypeResolver resolver, Int64& bytesRead, Boolean& haveObject, SerializationContext context) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 372
   at ProtoBuf.Serializer.DeserializeWithLengthPrefix[T](Stream source, PrefixStyle style, Int32 fieldNumber) in C:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 320
   at SoundFingerprinting.Storage.DAO.PersistenceUtils.ReadAllBut[T](String filename, Func`2 filter, Int32& filteredFields)
   at SoundFingerprinting.Storage.Replication.Log.LogPersistence.ReadAll[T](String filename)
   at SoundFingerprinting.Storage.Replication.Log.ReplicationLog.CheckRunningLog()
   at SoundFingerprinting.Storage.Replication.Log.ReplicationLog.Init()
   at SoundFingerprinting.Storage.Replication.ReplicationLogHandler..ctor(String baseDirectory, Int32 maxLogEntriesPerFile)
   at SoundFingerprinting.Storage.Servers.StorageFactory.NewLeader(Int32 port, String hostname, String baseDirectory, Int32 maxLogEntriesPerFile, Boolean enableTelemetry, String clusterKey, String multicastIp, Int32 multicastPort, Int32 gossipBroadcastDelay, Boolean includeInRotation, String queryMatchesFolder)
   at Emy.ArgsToStorageServiceExtension.ToStorageServer(Args arguments) in /Users/sergiuciumac/Documents/Projects/soundfingerprinting.storage/src/Emy/ArgsToStorageServiceExtension.cs:line 12
   at Emy.Program.Main(String[] args) in /Users/sergiuciumac/Documents/Projects/soundfingerprinting.storage/src/Emy/Program.cs:line 66
```
I'm sure doing a reinstall would fix it, but that seems extreme.

**Comment by AddictedCS** [comment]
Are you still running low on memory? Also, you can try deleting the last track that has been inserted by accessing /sfdata folder and removing `trackRef_<id>` with the largest ID.

**Comment by tmontney** [comment]
If by **memory** you mean hard drive space, yes. I have a few GB remaining. I figure it shouldn't become an issue until I'm under 500 MB. No person should be this low, but it still could be a fringe case (where running out of disk space can break the container). Hopefully I can resolve the low disk space in the next week.

**Comment by tmontney** [comment]
So I decided to reinstall after clearing some space. Got about 30 GB. Fingerprinting went fine this time, but now it seems unstable. I'm trying to compare my existing fingerprint set against ~1000 one minute .wav files, and see what matches. A few finds in and it starts throwing socket errors (server forcibly closed the connection). Sometimes I find the container is no longer running, but can manually restart it.

**Comment by AddictedCS** [comment]
You need to check the logs on why is the container crashing. Also, in order to make it easier, I can send you the executables that will run directly on your host machine. My first guess is that the container is running out of RAM. How much RAM did you allocate for your Docker Engine?

**Comment by tmontney** [comment]
2 GB. I'll admit, I'm not terribly familiar with docker. I decided to reinstall docker entirely. I allocated 6 GB and am reindexing the collection.

I don't wanna muddy up this section, where can I reach out over general questions about the best ways to use docker? I see a tiny bit of documentation here and on the website.

**Comment by tmontney** [comment]
Original issue has not happened again.
