### ISSUE TITLE
Large wave file error

### ISSUE THREAD

**Issue by Viper512** [AddictedCS/soundfingerprinting#160]
**Describe the bug**
Using sample code from readme.md, to put store (and process and fingerprint) a track which is longer causes an overflow.

`An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.OverflowException : Arithmetic operation resulted in an overflow.
   at SoundFingerprinting.Audio.LowPassFilter.ResampleNonIntegerFactor(Single[] samples, Int32 p, Int32 q, Single[] filter)
   at SoundFingerprinting.Audio.LowPassFilter.FilterAndDownsample(Single[] samples, Int32 sourceSampleRate, Int32 targetSampleRate)
   at SoundFingerprinting.Audio.SoundFingerprintingAudioService.ToTargetSampleRate(Single[] monoSamples, Int32 sourceSampleRate, Int32 sampleRate)
   at SoundFingerprinting.Audio.SoundFingerprintingAudioService.ReadMonoSamplesFromFile(String pathToSourceFile, Int32 sampleRate, Double seconds, Double startAt)
   at SoundFingerprinting.Audio.AudioService.ReadMonoSamplesFromFile(String pathToSourceFile, Int32 sampleRate)
   at SoundFingerprinting.Command.FingerprintCommand.<>c__DisplayClass6_0.<From>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)`

I believe this is a problem of the max size of an array being over 2GB in total.

**To Reproduce**
1. Use : ` var hashedFingerprints = FingerprintCommandBuilder.Instance
                                        .BuildFingerprintCommand()
                                        .From(pathToAudioFile)
                                        .UsingServices(audioService)
                                        .Hash().Result;`
2. Use a large wave file (in my case 1 hour 55 minutes in length, 1536kbps bit rate, 1.25GB)

**Expected behavior**
Should work.

**Comment by AddictedCS** [comment]
Please use `FFmpegAudioService` to resample the file with 1536kbps bit rate.
Installation details can be found here: https://github.com/AddictedCS/soundfingerprinting/wiki/Supported-Audio-Formats
