### ISSUE TITLE
Possible to Speed Up?

### ISSUE THREAD

**Issue by Hamsterland** [AddictedCS/soundfingerprinting#161]
I have a small database of about 300 mp4s. I use this method to insert them into the service.
```cs
private static readonly IModelService modelService = new InMemoryModelService();
private static readonly IAudioService audioService = new FFmpegAudioService();

public async Task InsertSongsIntoService(List<Song> songs)
{
    for (var i = 0; i < songs.Count; i++)
    {
        var info = new TrackInfo($"{i}", songs[i].Title, songs[i].Artist);
        var path = songs[i].FullPath;
        
        var hashedFingerprints = await FingerprintCommandBuilder.Instance
            .BuildFingerprintCommand()
            .From(path)
            .UsingServices(audioService)
            .Hash();
        
        modelService.Insert(info, hashedFingerprints);
    }
}
```

Then, this method tries to match a song.

```cs
public async Task TryMatchSong(string path)
{
    const int secondsToAnalyze = 10; 
    const int startAtSecond = 0;
    
    var queryResult = await QueryCommandBuilder.Instance.BuildQueryCommand()
        .From(path, secondsToAnalyze, startAtSecond)
        .WithQueryConfig(new LowLatencyQueryConfiguration())
        .UsingServices(modelService, audioService)
        .Query();
    
    var result = !queryResult.ContainsMatches ? "No Match" : queryResult.BestMatch.Track.Title;
    Console.WriteLine(result);
}
```

The only problem is that when I provide a 15 second cut of a song to match, it takes a good minute to find. For my intended use case this is too slow, and the fact that I need to expand my database to around 2000 songs does not help.

Any suggestions on making this faster?

**Comment by AddictedCS** [comment]
What kind of model service do you use? In memory model service is not meant to be used outside testing environments.
Try Emy Community Edition.

**Comment by Hamsterland** [comment]
@AddictedCS where do I download the Emy files to run on Docker?

**Comment by AddictedCS** [comment]
`Emy` is available via Docker. 
Trying it is easy just run the command (make sure to change local `/persistent-dir` to whatever test folder you have :
```
docker run -d -v /persistent-dir:/app/data -p 3399:3399 -p 3340:3340 addictedcs/soundfingerprinting.emy:latest
```
Then in your test client substitute `InMemoryModelService` with `EmyModelService`, specifying the connection details.
```csharp
// connect to Emy on port 3399
var emyModelService = EmyModelService.NewInstance("localhost", 3399);
```
Now you can use the fingerprinting and query commands as usual.

**Comment by Hamsterland** [comment]
@AddictedCS Thank you, I have successfully switched to Emy. But now I am facing another problem. 
```cs
public async Task InsertSongsIntoService(List<Song> songs)
        {
            for (var i = 0; i < songs.Count; i++)
            {
                var info = new TrackInfo($"{i}", songs[i].Title, songs[i].Artist);
                var path = songs[i].FullPath;
                
                var hashedFingerprints = await FingerprintCommandBuilder.Instance // Exception here
                    .BuildFingerprintCommand()
                    .From(path)
                    .UsingServices(audioService)
                    .Hash();
                
                modelService.Insert(info, hashedFingerprints);
            }
        }
```
```
Unhandled exception. System.ApplicationException: Invalid argument
   at SoundFingerprinting.Emy.FFmpeg.Common.ErrorExtensions.ThrowExceptionIfError(Int32 error)
   at SoundFingerprinting.Emy.FFmpeg.Demuxer.OpenInputFile(String file)
   at SoundFingerprinting.Emy.FFmpeg.Demuxer..ctor(String file, MediaType mediaType)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadTrack(String file, MediaType mediaType)
   at SoundFingerprinting.Emy.FFmpegAudioService.GetAvTrack(String path, Int32 sampleRate)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadMonoSamplesFromFile(String path, Int32 sampleRate)
   at SoundFingerprinting.Command.FingerprintCommand.<>c__DisplayClass6_0.<From>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AMC.Audio.AudioMatcher.InsertSongsIntoService(List`1 songs) in C:\Users\mdabr\RiderProjects\AMC\AMC.Audio\AudioMatcher.cs:line 58
   at AMC.Program.Main(String[] args) in C:\Users\mdabr\RiderProjects\AMC\AMC\Program.cs:line 41
   at AMC.Program.<Main>(String[] args)

```

**Comment by AddictedCS** [comment]
This error indicates a problem with opening the file, most probably the location is invalid.
Make sure `songs[i].FullPath` points to the right location.

**Comment by Hamsterland** [comment]
@AddictedCS It's still kind of taking a while. I am using ffmpeg and Emy. I have around 300mp4s and to find a match from a 10 second audio clip it takes around 50 seconds. Any way to make this faster?

**Comment by Hamsterland** [comment]
Anything? :\

**Comment by AddictedCS** [comment]
What's the total length of the 300 mp4s that you've stored in the database? What is the capacity of the machine you are running the software on? Did you configure the Docker container to use all the available resources on it?

Community Edition will not provide algorithmic speedups anytime soon.
