### ISSUE TITLE
creating fingerprints failed for some mp3s

### ISSUE THREAD

**Issue by shuvuu** [AddictedCS/soundfingerprinting#166]
Not for all mp3s, but for some... I tried to re-encode mp3s with higher/lower quality without any success. 
emy community + ffmpeg
```
System.AggregateException: One or more errors occurred. (Invalid data found when processing input)
 ---> System.ApplicationException: Invalid data found when processing input
   at SoundFingerprinting.Emy.FFmpeg.Common.ErrorExtensions.ThrowExceptionIfError(Int32 error)
   at SoundFingerprinting.Emy.FFmpeg.Decoder.SendPacket(AVPacket* packet)
   at SoundFingerprinting.Emy.FFmpeg.Decoder.Decode(AVPacket* packet)
   at SoundFingerprinting.Emy.FFmpeg.Demuxer.Demux(Double seconds)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadAVTrack(String source, MediaType mediaType, Double seconds, Int32 count, CancellationToken cancellationToken)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadTrack(String file, MediaType mediaType, Double seconds)
   at SoundFingerprinting.Emy.FFmpegAudioService.GetAvTrack(String path, Int32 sampleRate, Double seconds)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadMonoSamplesFromFile(String path, Int32 sampleRate)
   at SoundFingerprinting.Command.FingerprintCommand.<>c__DisplayClass6_0.<From>b__0() in            src\SoundFingerprinting\Command\FingerprintCommand.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```

**Comment by AddictedCS** [comment]
Can you give an example mp3 which fail to be processed?

**Comment by shuvuu** [comment]
For example this file gave same error - https://share.mobinet.mn/file/63wghd73qo9t/55_shaggy_ft._akon_-_whats_love.47423.mp3

**Comment by AddictedCS** [comment]
The example that you've sent me contains corrupted concatenated streams (5 different streams?):
```
[mp3float @ 0x7fee57016800] Header missing106.8kbits/s speed=58.9x
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x7fee57016800] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x7fee57016800] overread, skip -5 enddists: -3 -3
[mp3float @ 0x7fee57016800] Header missing118.2kbits/s speed=59.1x
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x7fee57016800] Header missing127.2kbits/s speed=57.7x
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x7fee57016800] overread, skip -6 enddists: -3 -3
[mp3float @ 0x7fee57016800] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 0x7fee57016800] Header missing115.1kbits/s speed=58.3x
Error while decoding stream #0:0: Invalid data found when processing input
```

To fix that you can re-encode with `ffmpeg` again:
```
ffmpeg -i 55_shaggy_ft._akon_-_whats_love.47423.mp3 fixed.mp3
```

Then used fixed.mp3 for indexing.

**Comment by shuvuu** [comment]
Hi, 
it's strange.. it doesn't solve the problem. But I found solution... 
`register_song(string songPath)
{
try { .. create fp & save... }
catch (ex) { .. ffmpeg re-encode.... fixed.mp3 }
finally { register_song(fixed.mp3) } 
}`
somehow this 2nd try works.

**Comment by shuvuu** [comment]
Hi,
it's strange.. it doesn't solve the problem. fixed.mp3s also gave errors. But I found solution...

> `register_song(string songPath) { 
> try { .. create fp & save... } 
> catch (ex) { .. ffmpeg re-encode.... fixed.mp3 (actually, this is optional) } 
> finally { register_song(fixed.mp3) } }`

somehow this 2nd try works.

**Comment by AddictedCS** [comment]
The problem is with the original encoding. It is missing mp3 headers due to erroneous concatenation.
You can use `ffplay` to verify the integrity of the files and it will show you the issues I've outlined above.
Second pass just happen to fix them, though you better take a look at why the original file is corrupted.
