### ISSUE TITLE
Avutil.56 is not found - The Specified module cannot be found

### ISSUE THREAD

**Issue by jeffward01** [AddictedCS/soundfingerprinting#168]
**Machine:**
Windows 10 OS

**Describe the bug**
I have uploaded some test songs and videos to the Emy Dashboard.  Now I am running the [.NET code here](https://emysound.readme.io/reference/query-1) to find matches.

When I run the demo code snippet from above, I receive this error:

```
System.DllNotFoundException: Unable to load DLL 'avutil.56': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
   at FFmpeg.AutoGen.ffmpeg.<>c.<LoadLibrary>b__14_0(String x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
   at FFmpeg.AutoGen.ffmpeg.<>c.<LoadLibrary>b__14_0(String x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__5_318()
   at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
   at SoundFingerprinting.Emy.FFmpeg.Demuxer.OpenInputFile(String file)
   at SoundFingerprinting.Emy.FFmpeg.Demuxer..ctor(String file, MediaType mediaType, CancellationToken cancellationToken)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadAVTrack(String source, MediaType mediaType, Double seconds, Int32 count, CancellationToken cancellationToken)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadTrack(String file, MediaType mediaType, Double seconds)
   at SoundFingerprinting.Emy.FFmpegAudioService.GetAvTrack(String path, Int32 sampleRate, Double seconds)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadMonoSamplesFromFile(String path, Int32 sampleRate)
   at SoundFingerprinting.Command.FingerprintCommand.<>c__DisplayClass6_0.<From>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at SoundFingerprinting.Command.QueryCommand.Query(DateTime relativeTo)
   at SoundFingerprinting.Command.QueryCommand.Query()
   at SoundFinger.Sandbox.ConsoleApp.FindMatch(FileInfo fileInfo) in C:\Dev\PlayGround\SoundFingerprinting\SoundFinger.Sandbox\SoundFinger.Sandbox\ConsoleApp.cs:line 89
   at SoundFinger.Sandbox.ConsoleApp.RunAsync() in C:\Dev\PlayGround\SoundFingerprinting\SoundFinger.Sandbox\SoundFinger.Sandbox\ConsoleApp.cs:line 60
```
I have done some google-fu and searching online to see how I can resolve the AvUtil.56 error and cannot find a solution.

Is this a common error?

Thanks!

**Comment by jeffward01** [comment]
I believe I have fixed it by installing FFMPEG in this specific directory: https://ibb.co/hBL8qsj which is explained [here in the docs](https://emysound.readme.io/reference/configuring-ffmpegaudioservice#:~:text=If%20you%20intend%20to%20fingerprint%20audio%20content%20encoded%20in%20various%20formats%20(i.e.%2C%20.mp3%2C%20.ogg%2C%20.flac%2C%20.ts%2C%20.mp4%2C%20etc.%2C)%20the%20package%20comes%20bundled%20with%20FFmpegAudioService.%20It%20uses%20native%20FFmpeg%20library%20thus%20you%20need%20to%20install%20FFmpeg%20binaries%20separately%20to%20make%20FFmpegAudioService%20work%3A).

**Comment by AddictedCS** [comment]
You need native FFmpeg libraries in the destination folder. You can find installation instructions here: https://github.com/AddictedCS/soundfingerprinting/wiki/Supported-Audio-Formats

**Comment by jeffward01** [comment]
I am using my API keys and code supplied from the Emy Documenation pages.  I am receiving the error: `"Server forcibly closed the connection from the client"`

![image](https://user-images.githubusercontent.com/12589359/128155382-3fd459a3-483a-4853-9d81-d4f8ef97cc89.png)

**Comment by jeffward01** [comment]
> You need native FFmpeg libraries in the destination folder. You can find installation instructions here: https://github.com/AddictedCS/soundfingerprinting/wiki/Supported-Audio-Formats

Thank you! I believe I have solved this and added the steps to resolve it in my reply. I appreciate the reply!

I have a new issue with connecting to the server that I have [referenced above](https://github.com/AddictedCS/soundfingerprinting/issues/168#issuecomment-892499824).  Any idea what could be the issue?

**Comment by AddictedCS** [comment]
Can you send me the file you are using for the query?

**Comment by AddictedCS** [comment]
I've identified the issue - readme.io have changed the way the examples are generated when a file is attached to the payload.
So, in order to insert/query use the following `curl` commands:

```bash
curl -X POST "https://api.emysound.com/api/v1/Query?mediaType=Audio&minConfidence=0.2&registerMatches=true" -H  "accept: application/json" -H  "Authorization: Basic <YOUR KEY>" -H  "Content-Type: multipart/form-data" -F "file=@do_not_go.wav;type=audio/x-wav"
```
Obviously, the command has to be executed from the folder where (in this case) `do_not_go.wav` file resides.

I've opened a ticket to check if they can fix the problem with their code generator: https://docs.readme.com/discuss/610a97704de52c0109855c3a

On a different note, since you are executing .NET code anyways you can try querying it from you dev-env: https://emysound.readme.io/reference/query-1
I've commended why you got the bitrate issue in issue #169, just use `FFmpegAudioService` and you should be good.

Hope it helps.
