### ISSUE TITLE
Issue on generating video fingerprints

### ISSUE THREAD

**Issue by huziyuan1090** [AddictedCS/soundfingerprinting#176]
I am interested in your work on video fingerprinting released in version 8.0.0. When I tried to test your latest code using mp4 videos from your website (https://emysound.com/blog/open-source/2021/08/01/video-fingerprinting.html), the program seems to stop at function From() in the file FingerprintCommand.cs. After much of debuging, I traced the problem down to the function mediaService.ReadAVTrackFromFile(). Without having access to the source code in SoundFingerprinting.Emy, I cannot get more detail beyond this point. Any idea or suggestion on resolving this issue?

**Comment by AddictedCS** [comment]
Did you receive any exceptions?
The example that is outlined [here][example] should work as intended.
In case it persists, just show the example of how are you trying to generate video fingerprints.


[example]: https://github.com/AddictedCS/soundfingerprinting/wiki/Video-Fingerprints

**Comment by B0BL0L** [comment]
Hi, I think the OP and me have the same problem, and I want to provide some example code and a stack trace.
The Code is working when using "MediaType.Video" but not when using "MediaType.Video". I also tried different video files and formats, but the outcome stayed the same. 

My code (basically example code):
// use FFmpegAudioService
var audioService = new FFmpegAudioService();


// create fingerprints
var hashedFingerprints = await FingerprintCommandBuilder.Instance
                                 .BuildFingerprintCommand()
                                 .From(pathToAudioFile, MediaType.Video)
                                 .UsingServices(audioService)
                                 .Hash();

Stack trace:
Unhandled exception. System.ApplicationException: Invalid argument
   at SoundFingerprinting.Emy.FFmpeg.Common.ErrorExtensions.ThrowExceptionIfError(Int32 error)
   at SoundFingerprinting.Emy.FFmpeg.Video.VideoFilter.InitFilters(String filters)
   at SoundFingerprinting.Emy.FFmpeg.Video.VideoFilter..ctor(String filters, VideoFormat input)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.<>c__DisplayClass11_0.<CreateVideoBlackFrameDetectors>b__0(VideoFilter fpsFilter, VideoFormat format)
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.CreateVideoBlackFrameDetectors(List`1 fpsFilters, List`1 formats, VideoTrackReadConfiguration configuration)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadAVTrack(String source, MediaType mediaType, Double seconds, Int32 count, AVTrackReadConfiguration avTrackReadConfiguration, CancellationToken cancellationToken)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadTrack(String file, MediaType mediaType, Double seconds, AVTrackReadConfiguration configuration)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadAVTrackFromFile(String pathToFile, AVTrackReadConfiguration configuration, MediaType mediaType)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadFramesFromFile(String pathToFile, VideoTrackReadConfiguration configuration, Double seconds, Double startsAt)
   at SoundFingerprinting.Command.FingerprintCommand.<>c__DisplayClass13_0.<From>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by AddictedCS** [comment]
Did you setup the FFmpeg library on your environment?
Details on FFmpeg setup can be found here: https://github.com/AddictedCS/soundfingerprinting/wiki/Audio-Services

**Comment by B0BL0L** [comment]
Yes, I downloaded the "ffmpeg-4.3.2-full_build-shared" release and copied the content of the bin folder alongside the exe in the "FFmpeg\bin\x64" directory. FFmpeg seems to work since audio fingerprints are generated for every filetype e.g. mp4. Only Video fingerprinting is not working.

**Comment by AddictedCS** [comment]
Can you link a media file that throws the exception?

**Comment by B0BL0L** [comment]
I have tried several videos and formats e.g. https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4

**Comment by AddictedCS** [comment]
I can't reproduce it. 

Operating system: Windows 7
I've downloaded the FFmpeg executables from [here](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.2-full_build-shared.7z) (ffmpeg v4.3.2).
Placed in the contents of the `bin` folder into `FFmpeg\bin\x64` folder which is alongside a sample executable that runs the following code (console app .NET 6):

```csharp
using SoundFingerprinting.Builder;
using SoundFingerprinting.Data;
using SoundFingerprinting.Emy;

var mediaService = new FFmpegAudioService();

var avHashes = await FingerprintCommandBuilder.Instance
    .BuildFingerprintCommand()
    .From("file_example_MP4_480_1_5MG.mp4", MediaType.Video)
    .UsingServices(mediaService)
    .Hash();


// See https://aka.ms/new-console-template for more information
Console.WriteLine($"{avHashes}");
Console.ReadKey();

```

The output is the following:
`Audio:[], Video:[Hashes[Count:900, Length:29.97]]`


I've tried it on macOS as well, it works as expected (ffmpeg version 4.4.1).

For media type `Audio | Video` I get the following:
```
Audio:[Hashes[Count:0, Length:30.39]], Video:[Hashes[Count:900, Length:29.97]]
```
Is there anything I'm missing here? If you still get the error we can get on a call to understand what's missing.

**Comment by B0BL0L** [comment]
I get the error with the same setup. The only difference is that I am using Windows 10. I am also using Visual Studio 2022.

**Comment by AddictedCS** [comment]
I've tried on Windows 11 as well it works as expected.
I'm linking the executable of the above code with all the required DLLs. You can download it from here: https://www.dropbox.com/s/6pvgycahotou48t/dec25thbug.zip?dl=0

The last thing that may be causing this issue is compiler setting Platform x86, though I'm inclined to believe you haven't set it explicitly.
Let me know if linked executable fails on your environment.

**Comment by B0BL0L** [comment]
With your executable, I get the same error message.

**Comment by AddictedCS** [comment]
Are you running it on Windows 10 64 bit architecture? You can check it in Settings > System > About.

**Comment by B0BL0L** [comment]
Yes, 64 bit Windows and 64 bit architecture.

**Comment by AddictedCS** [comment]
At this point will wait for more reports, as it seems it's smth related to you particular setup which I can't reproduce.

**Comment by B0BL0L** [comment]
Thank you for your effort!

**Comment by AddictedCS** [comment]
The VM that I've build the executable for Windows is this one (Windows 11 Enterprise): https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
You can try it on your own see if it works, I will be quite surprised if it doesn't.

**Comment by B0BL0L** [comment]
It is working. Your dropbox sample and performed with visual studio. Using a vm is also sufficient for the stuff I want to do.
Thank you for the time you took for helping me. You are a really nice guy!

**Comment by AddictedCS** [comment]
Great to hear it works!
