### ISSUE TITLE
FFmpegAudioService does not find ffmpeg installation

### ISSUE THREAD

**Issue by Goffen** [AddictedCS/soundfingerprinting#179]
**Describe the bug**
Im trying to just start an FFmpegAudioService but it crashes.

**To Reproduce**
1.  brew install ffmpeg (installs by default to /opt/homebrew/opt/ffmpeg apparently)
2. run test code
3. See error

**Expected behavior**
Not an error and the library to locate `libavformat.58.dylib` in `/opt/homebrew/opt/ffmpeg/lib`

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.1

** Stacktrace ** 
`Hello, World!
FFmpeg set to root path /usr/local/lib/
FFmpeg library failed to load. Read here for details on how to install FFmpeg on your machine: https://github.com/AddictedCS/soundfingerprinting/wiki/Audio-Services
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'avformat.58': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_318()
   at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
   at SoundFingerprinting.Emy.FFmpeg.Demuxer.OpenInputFile(String file)
   at SoundFingerprinting.Emy.FFmpeg.Demuxer..ctor(String file, MediaType mediaType, CancellationToken cancellationToken)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadAVTrack(String source, MediaType mediaType, Double seconds, Int32 count, AVTrackReadConfiguration avTrackReadConfiguration, CancellationToken cancellationToken)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SoundFingerprinting.Emy.AudioVideo.Data.FFmpegDataService.ReadTrack(String file, MediaType mediaType, Double seconds, AVTrackReadConfiguration configuration)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadAVTrackFromFile(String pathToFile, AVTrackReadConfiguration configuration, Double seconds, Double startsAt, MediaType mediaType)
   at SoundFingerprinting.Emy.FFmpegAudioService.GetAudioTrack(String path, Int32 sampleRate, Double seconds)
   at SoundFingerprinting.Emy.FFmpegAudioService.ReadMonoSamplesFromFile(String path, Int32 sampleRate, Double seconds, Double startAt)
   at SoundFingerprinting.Command.FingerprintCommand.<>c__DisplayClass13_0.<From>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in /Users/goff/RiderProjects/LmdAudioSplitter/LmdAudioSplitterConsole/Program.cs:line 20
   at Program.<Main>(String[] args)
`

**Comment by AddictedCS** [comment]
Can you execute `ffmpeg` in the terminal and copy-paste the results of it here?
You should get smth like this:
```
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

**Comment by Goffen** [comment]
```
➜  ~ ffmpeg
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/4.4.1_5 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by AddictedCS** [comment]
Are you running Monterey on Apple Silicon? 
It seems homebrew has changed the target directory for ARM MacBook models. Where exactly is homebrew installing and referencing the symlinks to `libav*.dylibs`?
Is it `/opt/homebrew/lib`? Can you list the `/opt/homebrew/lib` see if you can find `libavformat.dylib` reference.
It should contain a link to libavformat similar to the following:
```
lrwxr-xr-x  1 sergiuciumac  staff    46B Jan  7 18:29 /usr/local/lib/libavformat.dylib -> ../Cellar/ffmpeg/4.4.1_5/lib/libavformat.dylib
```

**Comment by Goffen** [comment]
Ah yes! Im running on m1 pro. Sorry I thought Monterey was only for those devices. 

```
➜  lib git:(stable) ls -lt | grep libavformat
lrwxr-xr-x    1 goff  admin    46 Jan  7 16:00 libavformat.dylib -> ../Cellar/ffmpeg/4.4.1_5/lib/libavformat.dylib
lrwxr-xr-x    1 goff  admin    42 Jan  7 16:00 libavformat.a -> ../Cellar/ffmpeg/4.4.1_5/lib/libavformat.a
lrwxr-xr-x    1 goff  admin    49 Jan  7 16:00 libavformat.58.dylib -> ../Cellar/ffmpeg/4.4.1_5/lib/libavformat.58.dylib
lrwxr-xr-x    1 goff  admin    56 Jan  7 16:00 libavformat.58.76.100.dylib -> ../Cellar/ffmpeg/4.4.1_5/lib/libavformat.58.76.100.dylib
```

**Comment by AddictedCS** [comment]
I've published a fix in [v8.2.1][emy-nuget], which includes `/opt/homebrew/lib` in probe paths for OSx operating systems.
Let me know if it worked for you.

[emy-nuget]: https://www.nuget.org/packages/SoundFingerprinting.Emy/8.2.1

**Comment by Goffen** [comment]
`FFmpeg set to root path /opt/homebrew/lib`

Very nice! Thanks a lot! Now I'm gonna try if this lib is useful for my idea ;)

**Comment by Goffen** [comment]
@AddictedCS I've experimented with it a bit now and I get no matches and maybe you can answer a question? 

I was planning on using this lib to recognise small short sounds from a larger video. The sounds are less than a second. You mentioned on in the README it cannot be used for speech recognition because 1.48 fingerprints. Does the sounds need to be longer than that?
