### ISSUE TITLE
Unable to resolve sub-type of: SoundFingerprinting.DAO.IModelReference

### ISSUE THREAD

**Issue by unt1tled** [AddictedCS/soundfingerprinting#91]
When attempting to use the snapshot function in InMemoryModelService, I'm getting the following error:

`{System.InvalidOperationException: Unable to resolve sub-type of: SoundFingerprinting.DAO.IModelReference
   at ProtoBuf.Meta.MetaType.ApplyDefaultBehaviour() in C:\code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 528
   at ProtoBuf.Meta.RuntimeTypeModel.FindOrAddAuto(Type type, Boolean demand, Boolean addWithContractOnly, Boolean addEvenIfAutoDisabled) in C:\code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 610
   at ProtoBuf.Meta.RuntimeTypeModel.GetKey(Type type, Boolean demand, Boolean getBaseKey) in C:\code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 794
   at ProtoBuf.Meta.ValueMember.TryGetCoreSerializer(RuntimeTypeModel model, DataFormat dataFormat, Type type, WireType& defaultWireType, Boolean asReference, Boolean dynamicType, Boolean overwriteList, Boolean allowComplexTypes) in C:\code\protobuf-net\src\protobuf-net\Meta\ValueMember.cs:line 713
   at ProtoBuf.Meta.ValueMember.BuildSerializer() in C:\code\protobuf-net\src\protobuf-net\Meta\ValueMember.cs:line 501
   at ProtoBuf.Meta.MetaType.BuildSerializer() in C:\code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 411
   at ProtoBuf.Meta.MetaType.get_Serializer() in C:\code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 387
   at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 809
   at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 46
   at proto_3(Object , ProtoWriter )
   at ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in C:\code\protobuf-net\src\protobuf-net\ProtoWriter.cs:line 46
   at proto_1(Object , ProtoWriter )
   at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value)
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context)
   at SoundFingerprinting.InMemory.RAMStorage.Snapshot(String path)
   at SoundFingerprinting.InMemory.InMemoryModelService.Snapshot(String path)
}`

**Comment by unt1tled** [comment]
It seems to be an issue with 2.3.2 version of protobuf-net. Updating it to 2.3.7 resolved the issue for me.

**Comment by AddictedCS** [comment]
Which version of SoundFingerprinting were you using?

**Comment by unt1tled** [comment]
5.2.1 with a netstandard2.0 project.

**Comment by AddictedCS** [comment]
Will check the compatibility in the next release. Hopefully will upgrade protobuf dependency to v2.3.7.
